language: go

go:
  - 1.10.x
  - master

services:
  - postgresql

before_script:
  - psql -U postgres -c "create user vsmt with password 'vsmt';"
  - psql -U postgres -c "create database vsmt with owner 'vsmt';"
  - cp .env_example .env

script: go test ./...

